<?php

namespace tr\rsywxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LakersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LakersRepository extends EntityRepository {

    public function getGames($year) {
        $span = 14 * 24 * 60 * 60; // 2 weeks
        $repo = $this->getEntityManager()->getRepository('trrsywxBundle:Lakers');
        $q = $repo->createQueryBuilder('g')
                ->where('g.year = :year')
                ->setParameter('year', $year)
                ->andWhere('g.dateplayed between :start and :end')
                ->setParameter('start', date('Y-m-d', time() - $span))
                ->setParameter('end', date('Y-m-d', time() + $span))
                ->orderBy('g.id')
                ->getQuery();

        return $q->getResult();
    }

    public function getWinLose($year, $winlose) {
        $em = $this->getEntityManager();
        $q = $em->createQuery("select count(l.id) g from trrsywxBundle:Lakers l where l.id>=0 and l.winlose='$winlose' and l.year=$year ");
        $summary = $q->getSingleResult();

        return $summary;
    }

    public function getYears() {
        $em = $this->getEntityManager();
        $q = $em->createQuery('select distinct(l.year) from trrsywxBundle:Lakers l order by l.year');

        $years = $q->getResult();
        return $years;
    }

}
