acme_agent:
    resource: "@AcmeAgentBundle/Controller/"
    type:     annotation
    prefix:   /

acme_client:
    resource: "@AcmeClientBundle/Resources/config/routing.yml"
    prefix:   /

trrsywx:
    resource: "@trrsywxBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

acme_account:
    resource: "@AcmeAccountBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    



