<?php

namespace Acme\AgentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends EntityRepository
{
}
