tr\rsywxBundle\Entity\BookPublisher:
    type: entity
    table: book_publisher
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
